version: '2'

services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    environment:
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    volumes:
      - ./init-script/:/docker-entrypoint-initdb.d/