name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: docker-compose -f docker-compose.bdd.yaml build && docker-compose -f docker-compose.bdd.yaml run --rm test && docker-compose -f docker-compose.bdd.yaml down  --remove-orphans
